#pragma once

/**
 * type of component
 */
enum {
	DF_COMPONENT_ACTOR = 1024,
	DF_COMPONENT_LOGIC,
	DF_COMPONENT_AI,
	DF_COMPONENT_INF,
	DF_COMPONENT_INF_ELEVATOR,
	DF_COMPONENT_INF_ELEVATOR_LIGHT,
	DF_COMPONENT_INF_ELEVATOR_MOVE_FLOOR,
	DF_COMPONENT_INF_ELEVATOR_MOVE_CEILING,
	DF_COMPONENT_INF_ELEVATOR_INV,
	DF_COMPONENT_INF_ELEVATOR_DOOR,
	DF_COMPONENT_INF_ELEVATOR_BASIC,
	DF_COMPONENT_INF_ELEVATOR_MORPH_SPIN1,
	DF_COMPONENT_INF_ELEVATOR_MORPH_SPIN2,
	DF_COMPONENT_INF_ELEVATOR_MORPH_MOVE1,
	DF_COMPONENT_TRIGGER,
	DF_COMPONENT_SIGN,
	DF_COMPONENT_WEAPON,
	DF_COMPONENT_SPRITE
};
